name: Receive Token Update

on:
  repository_dispatch:
    types: [tokens-updated]

jobs:
  update-tokens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout consumer repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}  # Needed if the submodule repo is private

      - name: Pull latest tokens from submodule
        run: |
          git submodule update --init --force
          cd sdx-figama-dictionary
          git fetch origin
          git checkout origin/main -- .
          cd ..

      - name: Debug path structure
        run: |
          echo "PWD: $(pwd)"
          ls -la
          echo "\nContents of sdx-figama-dictionary:"
          ls -la sdx-figama-dictionary || echo "❌ sdx-figama-dictionary directory not found!"
          echo "\nContents of sdx-figama-dictionary/output:"
          ls -la sdx-figama-dictionary/output || echo "❌ output directory not found!"

      - name: Copy pre-built CSS to lib/styles folder
        run: |
          mkdir -p lib/styles
          cp sdx-figama-dictionary/output/fixed-tokens.css lib/styles/tokens.css

      - name: Commit & push changes
        run: |
          git config user.name "anand-ceindia"
          git config user.email "itadmin@contentenablers.com"
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/contentenablers/ceui.git
          git add lib/styles/tokens.css
          git commit -m "feat:♻️ Update token CSS from submodule" || echo "No changes to commit"
          git push
