name: Receive Token Update

on:
  repository_dispatch:
    types: [tokens-updated]

jobs:
  update-tokens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout consumer repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}  # Needed if the submodule repo is private

      - name: Pull latest tokens from submodule
        run: |
          git submodule update --init --force
          cd sdx-figama-dictionary
          git fetch origin
          git checkout origin/main -- .
          cd ..

      - name: Debug path structure
        run: |
          echo "PWD: $(pwd)"
          ls -la
          echo "\nContents of figma-design-tokens:"
          ls -la figma-design-tokens || echo "❌ figma-design-tokens directory not found!"
          echo "\nContents of figma-design-tokens/output:"
          ls -la figma-design-tokens/output || echo "❌ figma-design-tokens/output directory not found!"

      - name: Copy pre-built CSS to public folder
        run: |
          mkdir -p public/styles
          cp sdx-figama-dictionary/output/fixed-tokens.css public/styles/tokens.css # Assuming singular 'token'

      - name: Commit & push changes
        run: |
            git config user.name "anand-ceindia"
            git config user.email "itadmin@contentenablers.com"
            git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/contentenablers/ceui.git
            git add public/styles/tokens.css
            git commit -m "feat:♻️ Update token CSS from submodule" || echo "No changes to commit"
            git push
