
# release action with semantic release
name: Release

on:
  ## only manually release for now
  workflow_dispatch:


jobs:
  release:
    name: Release to NPM
    permissions:
      contents: write
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Compile TypeScript to generate types
        run: npx tsc
      - name: Building package
        run: npm run build        
      - name: Semantic Release
        run: npx semantic-release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
